// Copyright 2025-2026 Lablup Inc. and Jeongkyu Shin
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// This module ports the KVarN method (Muller et al., arXiv 2606.03458,
// Apache-2.0) to mlxcel, following the mlx-kvarn community reference
// implementation (github.com/eplt/mlx-kvarn). Unit tests are pinned to
// vectors generated BY that reference implementation (see
// scripts/export_kvarn_fixtures.py) — "verified" here means verified
// against the reference's actual output, not a re-derivation of its math.

//! KVarN tile quantization: Hadamard rotation → Sinkhorn variance
//! normalization → per-row asymmetric RTN.
//!
//! Pipeline (write side, per `[N, R, C]` batch of tiles — R tokens,
//! C = head_dim, both 128 for MiniMax-M3):
//!
//! 1. **Hadamard rotate** along the channel axis (`crate::wht`, orthonormal,
//!    power-of-2 only — pinned by the WHT tests in `ffi_tests.rs`). Spreads
//!    outlier-channel energy uniformly so no channel dominates a scale.
//! 2. **Sinkhorn** ([`sinkhorn_normalize`]): log-domain alternating
//!    column/row std balancing with best-so-far tracking. Plain tensor ops.
//! 3. **Asymmetric RTN** ([`rtn_quantize_per_row`]): per-row min/max affine
//!    to `bits` (8 or 4), stored as one value per byte (`u8`). Sub-byte
//!    packing for the 4-bit path is deliberately NOT done at this layer —
//!    measure memory first; packing halves storage but adds unpack cost.
//!
//! The read side ([`kvarn_dequantize_rotated`]) reproduces the reference
//! dequantization exactly: `(q * scale + zp) * s_col * s_row`, still in the
//! rotated frame. Callers un-rotate with one more `wht` (self-inverse) when
//! they need standard-frame tensors.
//!
//! Why k8 ("KVarN-k8") when upstream presets stop at 4-bit: the 2026-07-08
//! decomposition experiment measured Hadamard+Sinkhorn+RTN8 at 4.7× lower
//! reconstruction error than the per-token absmax INT8 that failed the live
//! copy-precision gate, at identical 2× compression — and with isotropic
//! (rotation-spread) error instead of the structured kind that flips
//! near-tie argmax decisions. See
//! `PROPOSAL_kv_cache_quantization_investigation_2026-07-07.md` §1d.

use cxx::UniquePtr;

use crate::dtype;
use crate::ffi::{self, MlxArray};
use crate::ops::wht;

/// Sinkhorn std clip lower bound (reference `_CLIP_STD_MIN`).
const CLIP_STD_MIN: f32 = 1e-3;
/// Sinkhorn std clip upper bound (reference `_CLIP_STD_MAX`).
const CLIP_STD_MAX: f32 = 1e3;
/// Log-scale clip lower bound (reference `_LOG_S_MIN`). Deliberately
/// asymmetric: scales may shrink a loud row/column by e^10 but amplify a
/// quiet one by only e^0.3 ≈ 1.35× — amplifying near-silent channels would
/// amplify noise.
const LOG_S_MIN: f32 = -0.3;
/// Log-scale clip upper bound (reference `_LOG_S_MAX`).
const LOG_S_MAX: f32 = 10.0;

/// Sinkhorn iteration count. The reference module defaults to 16 but the
/// upstream README ships 4 as the verified setting; the 2026-07-08
/// decomposition experiment measured no practical error difference between
/// 4 and 16 on outlier-heavy tiles (0.07213 vs 0.07216 rel err at k4).
pub const KVARN_SINKHORN_ITERS: usize = 4;

/// Tile size in tokens. Matches MiniMax-M3's sparse block size and the
/// server prefill-alignment quantum — one stride everywhere.
pub const KVARN_TILE_TOKENS: i32 = 128;

/// Result of quantizing a batch of rotated tiles.
///
/// All tensors keep the tile batch axis `N` first. `q` stores one value per
/// byte regardless of `bits` (see module docs on deferred packing).
pub struct KvarnQuantizedTiles {
    /// `[N, R, C]` u8 codes in `[0, 2^bits - 1]`.
    pub q: UniquePtr<MlxArray>,
    /// `[N, R, 1]` f32 per-row RTN scale.
    pub scale: UniquePtr<MlxArray>,
    /// `[N, R, 1]` f32 per-row RTN zero-point (the row minimum).
    pub zp: UniquePtr<MlxArray>,
    /// `[N, 1, C]` f32 Sinkhorn per-column scales.
    pub s_col: UniquePtr<MlxArray>,
    /// `[N, R, 1]` f32 Sinkhorn per-row scales.
    pub s_row: UniquePtr<MlxArray>,
    /// Bit width the codes were quantized to (8 or 4).
    pub bits: u8,
}

/// Hadamard-rotate along the last axis. Thin, documented alias for
/// [`crate::wht`]: orthonormal (1/√N convention), self-inverse, power-of-2
/// last dim only — callers guard head_dim before reaching this module.
pub fn kvarn_rotate(x: &MlxArray) -> UniquePtr<MlxArray> {
    wht(x)
}

/// Population→sample std along `axis`, clipped to the Sinkhorn band.
///
/// Matches the reference exactly: `sqrt(max(E[x²] − E[x]², 0) · n/(n−1))`
/// then clip to `[CLIP_STD_MIN, CLIP_STD_MAX]`. The Bessel factor is part
/// of the pinned behavior (mutation that must turn the fixture tests red:
/// dropping the `n/(n−1)`).
fn clipped_std_along(x: &MlxArray, axis: i32, n: i32) -> UniquePtr<MlxArray> {
    let mean = ffi::mean_axis(x, axis, true);
    let sq_mean = ffi::mean_axis(&ffi::multiply(x, x), axis, true);
    let var = ffi::subtract(&sq_mean, &ffi::multiply(&mean, &mean));
    let bessel = n as f32 / (n - 1) as f32;
    let var = ffi::maximum(
        &crate::ops::multiply_scalar(&var, bessel),
        &ffi::full_like(&var, 0.0),
    );
    let std = ffi::sqrt(&var);
    ffi::clip(
        &std,
        &ffi::full_like(&std, CLIP_STD_MIN),
        &ffi::full_like(&std, CLIP_STD_MAX),
    )
}

/// Scalar imbalance metric of a `[N, R, C]` batch: `col_max/col_min +
/// row_max/row_min` over the GLOBAL batch (a perfectly balanced batch scores
/// 2.0).
///
/// Faithful-to-reference quirk, kept deliberately: the reference's batched
/// path annotates this `[N, 1, 1]` but computes `mx.max(...)` with no axis —
/// a GLOBAL scalar — so best-so-far selection is batch-global, not per-tile.
/// The pinned fixtures encode that behavior; changing it to per-tile would
/// be a (possibly better) deviation to take consciously, with regenerated
/// fixtures, not by accident.
fn imbalance(x: &MlxArray) -> UniquePtr<MlxArray> {
    let shape = ffi::array_shape(x);
    let (r, c) = (shape[shape.len() - 2], shape[shape.len() - 1]);
    let col_std = clipped_std_raw(x, -2, r);
    let row_std = clipped_std_raw(x, -1, c);
    let col_ratio = ffi::divide(
        &ffi::max_all(&col_std),
        &ffi::maximum(
            &ffi::min_all(&col_std),
            &ffi::full_f32(&[], 1e-8, dtype::FLOAT32),
        ),
    );
    let row_ratio = ffi::divide(
        &ffi::max_all(&row_std),
        &ffi::maximum(
            &ffi::min_all(&row_std),
            &ffi::full_f32(&[], 1e-8, dtype::FLOAT32),
        ),
    );
    ffi::add(&col_ratio, &row_ratio)
}

/// Std for the imbalance metric: Bessel-corrected but UNclipped (the
/// reference's `_imbalance` floors only the min at 1e-8, applied above).
fn clipped_std_raw(x: &MlxArray, axis: i32, n: i32) -> UniquePtr<MlxArray> {
    let mean = ffi::mean_axis(x, axis, true);
    let sq_mean = ffi::mean_axis(&ffi::multiply(x, x), axis, true);
    let var = ffi::subtract(&sq_mean, &ffi::multiply(&mean, &mean));
    let bessel = n as f32 / (n - 1) as f32;
    let var = ffi::maximum(
        &crate::ops::multiply_scalar(&var, bessel),
        &ffi::full_like(&var, 0.0),
    );
    ffi::sqrt(&var)
}

/// Log-domain Sinkhorn variance normalization over a `[N, R, C]` batch of
/// (already rotated) tiles.
///
/// Returns `(balanced, s_col, s_row)` with `balanced = tiles / s_col /
/// s_row`, `s_col: [N, 1, C]`, `s_row: [N, R, 1]` — the best-so-far scales
/// by the [`imbalance`] metric across `iterations` alternating column/row
/// passes. Faithful port of the reference `variance_normalize_batched`.
pub fn sinkhorn_normalize(
    tiles: &MlxArray,
    iterations: usize,
) -> (
    UniquePtr<MlxArray>,
    UniquePtr<MlxArray>,
    UniquePtr<MlxArray>,
) {
    let shape = ffi::array_shape(tiles);
    assert!(
        shape.len() == 3,
        "sinkhorn_normalize expects [N, R, C], got {shape:?}"
    );
    let (n, r, c) = (shape[0], shape[1], shape[2]);
    let tiles_f32 = ffi::astype(tiles, dtype::FLOAT32);

    let mut log_s_col = ffi::zeros(&[n, 1, c], dtype::FLOAT32);
    let mut log_s_row = ffi::zeros(&[n, r, 1], dtype::FLOAT32);

    let mut sc_best = ffi::exp(&log_s_col);
    let mut sr_best = ffi::exp(&log_s_row);
    let mut imb_best = imbalance(&tiles_f32);

    let clip_log = |v: &MlxArray| -> UniquePtr<MlxArray> {
        ffi::clip(
            v,
            &ffi::full_like(v, LOG_S_MIN),
            &ffi::full_like(v, LOG_S_MAX),
        )
    };

    let mut cur = ffi::astype(&tiles_f32, dtype::FLOAT32);
    for _ in 0..iterations {
        // Column pass.
        let col_std = clipped_std_along(&cur, -2, r);
        log_s_col = clip_log(&ffi::add(&log_s_col, &ffi::log(&col_std)));
        let s_col_lin = ffi::exp(&log_s_col);
        let s_row_lin = ffi::exp(&log_s_row);
        cur = ffi::divide(&ffi::divide(&tiles_f32, &s_col_lin), &s_row_lin);

        // Row pass.
        let row_std = clipped_std_along(&cur, -1, c);
        log_s_row = clip_log(&ffi::add(&log_s_row, &ffi::log(&row_std)));
        let s_col_lin = ffi::exp(&log_s_col);
        let s_row_lin = ffi::exp(&log_s_row);
        cur = ffi::divide(&ffi::divide(&tiles_f32, &s_col_lin), &s_row_lin);

        // Best-so-far (batch-global — see `imbalance` docs).
        let imb = imbalance(&cur);
        let better = ffi::less_equal(&imb, &imb_best);
        sc_best = ffi::where_cond(&better, &s_col_lin, &sc_best);
        sr_best = ffi::where_cond(&better, &s_row_lin, &sr_best);
        imb_best = ffi::minimum(&imb, &imb_best);
    }

    let balanced = ffi::divide(&ffi::divide(&tiles_f32, &sc_best), &sr_best);
    (balanced, sc_best, sr_best)
}

/// Per-row asymmetric round-to-nearest quantization of `[N, R, C]` balanced
/// tiles to `bits` (8 or 4). Returns `(q_u8, scale, zp)` with the exact
/// reference semantics: `scale = max((hi − lo)/qmax, 1e-10)`, `zp = lo`,
/// `q = clip(round((x − zp)/scale), 0, qmax)`.
pub fn rtn_quantize_per_row(
    tiles: &MlxArray,
    bits: u8,
) -> (
    UniquePtr<MlxArray>,
    UniquePtr<MlxArray>,
    UniquePtr<MlxArray>,
) {
    assert!(
        bits == 8 || bits == 4,
        "KVarN RTN supports bits 8 or 4, got {bits}"
    );
    let qmax = ((1u32 << bits) - 1) as f32;
    let lo = ffi::min_axis(tiles, -1, true);
    let hi = ffi::max_axis(tiles, -1, true);
    let range = ffi::subtract(&hi, &lo);
    let scale = ffi::maximum(
        &crate::ops::divide_scalar(&range, qmax),
        &ffi::full_like(&range, 1e-10),
    );
    let centered = ffi::divide(&ffi::subtract(tiles, &lo), &scale);
    let q = ffi::clip(
        &ffi::round(&centered),
        &ffi::full_like(&centered, 0.0),
        &ffi::full_like(&centered, qmax),
    );
    (ffi::astype(&q, dtype::UINT8), scale, lo)
}

/// Full write-side pipeline on ROTATED tiles: Sinkhorn → RTN.
///
/// Callers rotate first ([`kvarn_rotate`]) — rotation is per-token and can
/// happen on arrival, while Sinkhorn+RTN happen per full tile.
pub fn kvarn_quantize(tiles_rotated: &MlxArray, bits: u8) -> KvarnQuantizedTiles {
    let (balanced, s_col, s_row) = sinkhorn_normalize(tiles_rotated, KVARN_SINKHORN_ITERS);
    let (q, scale, zp) = rtn_quantize_per_row(&balanced, bits);
    KvarnQuantizedTiles {
        q,
        scale,
        zp,
        s_col,
        s_row,
        bits,
    }
}

/// Read-side dequantization back to the ROTATED frame:
/// `(q · scale + zp) · s_col · s_row`. One more [`kvarn_rotate`] (self-
/// inverse) yields standard-frame tensors.
pub fn kvarn_dequantize_rotated(t: &KvarnQuantizedTiles) -> UniquePtr<MlxArray> {
    let qf = ffi::astype(&t.q, dtype::FLOAT32);
    let de = ffi::add(&ffi::multiply(&qf, &t.scale), &t.zp);
    ffi::multiply(&ffi::multiply(&de, &t.s_col), &t.s_row)
}

#[cfg(test)]
mod tests {
    use super::*;

    // Fixtures generated by scripts/export_kvarn_fixtures.py from the
    // mlx-kvarn REFERENCE implementation (2 tiles, [2,128,128], f32 LE,
    // sinkhorn_iters=4, seed 42, ×40 outlier channels). Shapes per
    // kvarn_fixtures/manifest.json.
    const N: i32 = 2;
    const R: i32 = 128;
    const C: i32 = 128;

    fn fixture_f32(bytes: &'static [u8], shape: &[i32]) -> cxx::UniquePtr<MlxArray> {
        let n_expected: usize = shape.iter().product::<i32>() as usize;
        assert_eq!(bytes.len(), n_expected * 4, "fixture size mismatch");
        let vals: Vec<f32> = bytes
            .chunks_exact(4)
            .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
            .collect();
        ffi::from_slice_f32(&vals, shape)
    }

    fn fixture_u8_as_f32_array(bytes: &'static [u8], shape: &[i32]) -> cxx::UniquePtr<MlxArray> {
        let n_expected: usize = shape.iter().product::<i32>() as usize;
        assert_eq!(bytes.len(), n_expected, "fixture size mismatch");
        let vals: Vec<f32> = bytes.iter().map(|&b| b as f32).collect();
        ffi::from_slice_f32(&vals, shape)
    }

    /// Count of elements where |a − b| > 0.5 (i.e. integer codes differing).
    fn code_mismatch_count(a: &MlxArray, b: &MlxArray) -> f32 {
        let diff = ffi::abs(&ffi::subtract(a, b));
        let hits = ffi::greater(&diff, &ffi::full_like(&diff, 0.5));
        let count = ffi::sum_all(&ffi::astype(&hits, dtype::FLOAT32));
        ffi::eval(&count);
        ffi::item_f32(&count)
    }

    fn max_abs_rel_diff(a: &MlxArray, b: &MlxArray) -> (f32, f32) {
        let diff = ffi::abs(&ffi::subtract(a, b));
        let max_abs = ffi::max_all(&diff);
        let denom = ffi::maximum(&ffi::abs(b), &ffi::full_like(b, 1e-6));
        let max_rel = ffi::max_all(&ffi::divide(&diff, &denom));
        ffi::eval(&max_abs);
        ffi::eval(&max_rel);
        (ffi::item_f32(&max_abs), ffi::item_f32(&max_rel))
    }

    const INPUT: &[u8] = include_bytes!("kvarn_fixtures/input_tiles_f32.bin");
    const ROTATED: &[u8] = include_bytes!("kvarn_fixtures/rotated_f32.bin");
    const BALANCED: &[u8] = include_bytes!("kvarn_fixtures/balanced_f32.bin");
    const S_COL: &[u8] = include_bytes!("kvarn_fixtures/s_col_f32.bin");
    const S_ROW: &[u8] = include_bytes!("kvarn_fixtures/s_row_f32.bin");
    const Q8: &[u8] = include_bytes!("kvarn_fixtures/q8_u8.bin");
    const SCALE8: &[u8] = include_bytes!("kvarn_fixtures/scale8_f32.bin");
    const ZP8: &[u8] = include_bytes!("kvarn_fixtures/zp8_f32.bin");
    const DEQ_ROT8: &[u8] = include_bytes!("kvarn_fixtures/dequant_rot8_f32.bin");
    const Q4: &[u8] = include_bytes!("kvarn_fixtures/q4_u8.bin");

    /// Stage 1: our rotation reproduces the reference's rotated tiles.
    /// Mutation that must turn this red: any scale change on `wht` (the
    /// orthonormal 1/√N convention is load-bearing for round-trip).
    #[test]
    fn kvarn_rotate_matches_reference() {
        let x = fixture_f32(INPUT, &[N, R, C]);
        let rot = kvarn_rotate(&x);
        let expected = fixture_f32(ROTATED, &[N, R, C]);
        let (max_abs, _) = max_abs_rel_diff(&rot, &expected);
        assert!(
            max_abs < 1e-3,
            "rotation diverges from reference: {max_abs}"
        );
    }

    /// Stage 2: Sinkhorn balanced tiles + both scale vectors match the
    /// reference at 4 iterations. Mutations that must turn this red:
    /// dropping the Bessel n/(n−1); swapping the clip bounds; skipping the
    /// second (row) pass; best-so-far tracking removed.
    #[test]
    fn kvarn_sinkhorn_matches_reference() {
        let rot = fixture_f32(ROTATED, &[N, R, C]);
        let (balanced, s_col, s_row) = sinkhorn_normalize(&rot, 4);
        let exp_bal = fixture_f32(BALANCED, &[N, R, C]);
        let exp_sc = fixture_f32(S_COL, &[N, 1, C]);
        let exp_sr = fixture_f32(S_ROW, &[N, R, 1]);
        let (abs_b, _) = max_abs_rel_diff(&balanced, &exp_bal);
        let (_, rel_c) = max_abs_rel_diff(&s_col, &exp_sc);
        let (_, rel_r) = max_abs_rel_diff(&s_row, &exp_sr);
        assert!(abs_b < 1e-2, "balanced tiles diverge: max_abs={abs_b}");
        assert!(rel_c < 1e-3, "s_col diverges: max_rel={rel_c}");
        assert!(rel_r < 1e-3, "s_row diverges: max_rel={rel_r}");
    }

    /// Stage 3 (k8): RTN codes match the reference EXACTLY (integers), and
    /// scale/zp match tightly. Mutation that must turn this red: symmetric
    /// instead of asymmetric quantization (zp = 0), or qmax 256 vs 255.
    #[test]
    fn kvarn_rtn8_matches_reference_exactly() {
        let balanced = fixture_f32(BALANCED, &[N, R, C]);
        let (q, scale, zp) = rtn_quantize_per_row(&balanced, 8);
        let qf = ffi::astype(&q, dtype::FLOAT32);
        let expected = fixture_u8_as_f32_array(Q8, &[N, R, C]);
        // ±1 code tolerance on exact rounding boundaries would be defensible
        // across MLX versions; with the SAME MLX on both sides we hold exact.
        let mismatches = code_mismatch_count(&qf, &expected);
        assert_eq!(
            mismatches, 0.0,
            "{mismatches} q8 codes differ from reference"
        );

        let exp_scale = fixture_f32(SCALE8, &[N, R, 1]);
        let exp_zp = fixture_f32(ZP8, &[N, R, 1]);
        let (_, rel_s) = max_abs_rel_diff(&scale, &exp_scale);
        let (abs_z, _) = max_abs_rel_diff(&zp, &exp_zp);
        assert!(rel_s < 1e-4, "scale8 diverges: {rel_s}");
        assert!(abs_z < 1e-3, "zp8 diverges: {abs_z}");
    }

    /// Stage 3 (k4): same pinning at 4 bits.
    #[test]
    fn kvarn_rtn4_matches_reference_exactly() {
        let balanced = fixture_f32(BALANCED, &[N, R, C]);
        let (q, _, _) = rtn_quantize_per_row(&balanced, 4);
        let qf = ffi::astype(&q, dtype::FLOAT32);
        let expected = fixture_u8_as_f32_array(Q4, &[N, R, C]);
        let mismatches = code_mismatch_count(&qf, &expected);
        assert_eq!(
            mismatches, 0.0,
            "{mismatches} q4 codes differ from reference"
        );
    }

    /// Stage 4: rotated-frame dequantization matches the reference's
    /// dequant, i.e. the full read path reproduces what the write path
    /// stored, per the reference math.
    #[test]
    fn kvarn_dequant_rotated_matches_reference() {
        let rot = fixture_f32(ROTATED, &[N, R, C]);
        let tiles = kvarn_quantize(&rot, 8);
        let deq = kvarn_dequantize_rotated(&tiles);
        let expected = fixture_f32(DEQ_ROT8, &[N, R, C]);
        let (max_abs, _) = max_abs_rel_diff(&deq, &expected);
        assert!(
            max_abs < 5e-2,
            "rotated dequant diverges: max_abs={max_abs}"
        );
    }

    /// End-to-end roundtrip on the ORIGINAL tiles: rotate → quantize →
    /// dequantize → unrotate ≈ input, with the k8 error band from the
    /// decomposition experiment (rel_err ≈ 0.004; assert an order of
    /// margin). Also asserts the band is TIGHT: a fake pipeline that
    /// skipped Sinkhorn entirely would land near absmax-int8's error and
    /// fail the upper bound... while a broken one fails the lower bound of
    /// simply being finite and nonzero.
    #[test]
    fn kvarn_k8_end_to_end_roundtrip_error_band() {
        let x = fixture_f32(INPUT, &[N, R, C]);
        let rot = kvarn_rotate(&x);
        let tiles = kvarn_quantize(&rot, 8);
        let deq_rot = kvarn_dequantize_rotated(&tiles);
        let back = kvarn_rotate(&deq_rot); // self-inverse
        let diff = ffi::subtract(&back, &x);
        let num = ffi::sqrt(&ffi::sum_all(&ffi::multiply(&diff, &diff)));
        let den = ffi::sqrt(&ffi::sum_all(&ffi::multiply(&x, &x)));
        let rel = ffi::divide(&num, &den);
        ffi::eval(&rel);
        let rel = ffi::item_f32(&rel);
        assert!(rel < 0.02, "k8 roundtrip rel_err {rel} above expected band");
        assert!(
            rel > 1e-5,
            "k8 roundtrip rel_err {rel} suspiciously exact — \
                 is quantization actually happening?"
        );
    }
}

#[cfg(test)]
mod cache_integration_tests {
    use super::*;
    use crate::cache::{KVCache, KVCacheMode};

    /// Deterministic pseudo-random f32 in [-1, 1) — no MLX RNG plumbing
    /// needed, and fully reproducible across runs/platforms.
    fn lcg_data(n: usize, seed: u64) -> Vec<f32> {
        let mut state = seed;
        (0..n)
            .map(|_| {
                state = state
                    .wrapping_mul(6364136223846793005)
                    .wrapping_add(1442695040888963407);
                ((state >> 33) as f32 / (1u64 << 31) as f32) - 1.0
            })
            .collect()
    }

    /// End-to-end: a KVarN8 KVCache and an Fp16 KVCache fed IDENTICAL data
    /// through the real update_and_fetch, compared after every chunk.
    ///
    /// Chunk sizes exercise every split path in update_kvarn8:
    ///   200 → sink fills (128) + tail 72
    ///   100 → tail 172 → one tile quantized (128) + tail 44
    ///   1   → decode-shaped single, tail 45
    ///   83  → tail 128 → EXACT tile boundary (tile quantized, tail empty)
    ///   1   → first token into a fresh tail
    ///
    /// The k8 band from the decomposition experiment is rel_err ≈ 0.004 on
    /// f32 tiles; fp16 in/out adds ~1e-3. Assert mean-square relative error
    /// < 0.02 AND > 1e-6 (a bit-exact match would mean quantization never
    /// ran — the sink-only prefix IS expected to be near-exact, so the
    /// lower bound is asserted only once history tiles exist).
    #[test]
    fn kvarn8_cache_roundtrip_tracks_fp16_within_band() {
        let (b, h, d) = (1i32, 2i32, 64i32);
        let mut kvarn = KVCache::new_with_mode(KVCacheMode::KVarN8);
        let mut fp16 = KVCache::new_with_mode(KVCacheMode::Fp16);

        let mut total = 0i32;
        for (i, &chunk) in [200i32, 100, 1, 83, 1].iter().enumerate() {
            let n = (b * h * chunk * d) as usize;
            let k_data = lcg_data(n, 0xC1E_A0 + i as u64);
            let v_data = lcg_data(n, 0xB0_B0 + i as u64);
            let shape = [b, h, chunk, d];
            let mk = || {
                (
                    ffi::astype(&ffi::from_slice_f32(&k_data, &shape), dtype::FLOAT16),
                    ffi::astype(&ffi::from_slice_f32(&v_data, &shape), dtype::FLOAT16),
                )
            };
            let (k1, v1) = mk();
            let (k2, v2) = mk();
            let (qk, qv) = kvarn.update_and_fetch(k1, v1);
            let (rk, rv) = fp16.update_and_fetch(k2, v2);
            total += chunk;

            for (q, r, name) in [(&qk, &rk, "K"), (&qv, &rv, "V")] {
                assert_eq!(
                    ffi::array_shape(q),
                    ffi::array_shape(r),
                    "{name} shape mismatch after chunk {i}"
                );
                assert_eq!(ffi::array_shape(q)[2], total, "{name} window length");
                let qf = ffi::astype(q, dtype::FLOAT32);
                let rf = ffi::astype(r, dtype::FLOAT32);
                let diff = ffi::subtract(&qf, &rf);
                let num = ffi::sum_all(&ffi::multiply(&diff, &diff));
                let den = ffi::sum_all(&ffi::multiply(&rf, &rf));
                let rel = ffi::divide(&ffi::sqrt(&num), &ffi::sqrt(&den));
                ffi::eval(&rel);
                let rel = ffi::item_f32(&rel);
                assert!(
                    rel < 0.02,
                    "{name} rel_err {rel} above k8 band after chunk {i} (total={total})"
                );
                if total > 2 * KVARN_TILE_TOKENS {
                    // History tiles exist — quantization must be visible.
                    assert!(
                        rel > 1e-6,
                        "{name} suspiciously exact after chunk {i} — is \
                         quantization actually running?"
                    );
                }
            }
        }
    }

    /// The trim_front guard must keep refusing KVarN8 (tile state cannot be
    /// head-trimmed) — pin the guard's current behavior so a future edit
    /// widening the matches! turns this red instead of corrupting silently.
    #[test]
    fn kvarn8_trim_front_refuses() {
        let mut cache = KVCache::new_with_mode(KVCacheMode::KVarN8);
        let (b, h, d) = (1i32, 1i32, 64i32);
        let n = (b * h * 200 * d) as usize;
        let k = ffi::astype(
            &ffi::from_slice_f32(&lcg_data(n, 7), &[b, h, 200, d]),
            dtype::FLOAT16,
        );
        let v = ffi::astype(
            &ffi::from_slice_f32(&lcg_data(n, 8), &[b, h, 200, d]),
            dtype::FLOAT16,
        );
        let _ = cache.update_and_fetch(k, v);
        let trimmed = cache.trim_front(64);
        assert_eq!(
            trimmed, 0,
            "KVarN8 must refuse head-trimming (returned {trimmed})"
        );
    }
}
