// Copyright 2025-2026 Lablup Inc. and Jeongkyu Shin
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// This module ports the KVarN method (Muller et al., arXiv 2606.03458,
// Apache-2.0) to mlxcel, following the mlx-kvarn community reference
// implementation (github.com/eplt/mlx-kvarn). Unit tests are pinned to
// vectors generated BY that reference implementation (see
// scripts/export_kvarn_fixtures.py) — "verified" here means verified
// against the reference's actual output, not a re-derivation of its math.

//! KVarN tile quantization: Hadamard rotation → Sinkhorn variance
//! normalization → per-row asymmetric RTN.
//!
//! Pipeline (write side, per `[N, R, C]` batch of tiles — R tokens,
//! C = head_dim, both 128 for MiniMax-M3):
//!
//! 1. **Hadamard rotate** along the channel axis (`crate::wht`, orthonormal,
//!    power-of-2 only — pinned by the WHT tests in `ffi_tests.rs`). Spreads
//!    outlier-channel energy uniformly so no channel dominates a scale.
//! 2. **Sinkhorn** ([`sinkhorn_normalize`]): log-domain alternating
//!    column/row std balancing with best-so-far tracking. Plain tensor ops.
//! 3. **Asymmetric RTN** ([`rtn_quantize_per_row`]): per-row min/max affine
//!    to `bits` (8 or 4), stored as one value per byte (`u8`). Sub-byte
//!    packing for the 4-bit path is deliberately NOT done at this layer —
//!    measure memory first; packing halves storage but adds unpack cost.
//!
//! The read side ([`kvarn_dequantize_rotated`]) reproduces the reference
//! dequantization exactly: `(q * scale + zp) * s_col * s_row`, still in the
//! rotated frame. Callers un-rotate with one more `wht` (self-inverse) when
//! they need standard-frame tensors.
//!
//! Why k8 ("KVarN-k8") when upstream presets stop at 4-bit: the 2026-07-08
//! decomposition experiment measured Hadamard+Sinkhorn+RTN8 at 4.7× lower
//! reconstruction error than the per-token absmax INT8 that failed the live
//! copy-precision gate, at identical 2× compression — and with isotropic
//! (rotation-spread) error instead of the structured kind that flips
//! near-tie argmax decisions. See
//! `PROPOSAL_kv_cache_quantization_investigation_2026-07-07.md` §1d.

use cxx::UniquePtr;

use crate::dtype;
use crate::ffi::{self, MlxArray};
use crate::ops::wht;

/// Sinkhorn std clip lower bound (reference `_CLIP_STD_MIN`).
const CLIP_STD_MIN: f32 = 1e-3;
/// Sinkhorn std clip upper bound (reference `_CLIP_STD_MAX`).
const CLIP_STD_MAX: f32 = 1e3;
/// Log-scale clip lower bound (reference `_LOG_S_MIN`). Deliberately
/// asymmetric: scales may shrink a loud row/column by e^10 but amplify a
/// quiet one by only e^0.3 ≈ 1.35× — amplifying near-silent channels would
/// amplify noise.
const LOG_S_MIN: f32 = -0.3;
/// Log-scale clip upper bound (reference `_LOG_S_MAX`).
const LOG_S_MAX: f32 = 10.0;

/// Sinkhorn iteration count. The reference module defaults to 16 but the
/// upstream README ships 4 as the verified setting; the 2026-07-08
/// decomposition experiment measured no practical error difference between
/// 4 and 16 on outlier-heavy tiles (0.07213 vs 0.07216 rel err at k4).
pub const KVARN_SINKHORN_ITERS: usize = 4;

/// Tile size in tokens. Matches MiniMax-M3's sparse block size and the
/// server prefill-alignment quantum — one stride everywhere.
pub const KVARN_TILE_TOKENS: i32 = 128;

/// Result of quantizing a batch of rotated tiles.
///
/// All tensors keep the tile batch axis `N` first. `q` stores one value per
/// byte regardless of `bits` (see module docs on deferred packing).
pub struct KvarnQuantizedTiles {
    /// `[N, R, C]` u8 codes in `[0, 2^bits - 1]`.
    pub q: UniquePtr<MlxArray>,
    /// `[N, R, 1]` f32 per-row RTN scale.
    pub scale: UniquePtr<MlxArray>,
    /// `[N, R, 1]` f32 per-row RTN zero-point (the row minimum).
    pub zp: UniquePtr<MlxArray>,
    /// `[N, 1, C]` f32 Sinkhorn per-column scales.
    pub s_col: UniquePtr<MlxArray>,
    /// `[N, R, 1]` f32 Sinkhorn per-row scales.
    pub s_row: UniquePtr<MlxArray>,
    /// Bit width the codes were quantized to (8 or 4).
    pub bits: u8,
}

/// Hadamard-rotate along the last axis. Thin, documented alias for
/// [`crate::wht`]: orthonormal (1/√N convention), self-inverse, power-of-2
/// last dim only — callers guard head_dim before reaching this module.
pub fn kvarn_rotate(x: &MlxArray) -> UniquePtr<MlxArray> {
    wht(x)
}

/// Population→sample std along `axis`, clipped to the Sinkhorn band.
///
/// Matches the reference exactly: `sqrt(max(E[x²] − E[x]², 0) · n/(n−1))`
/// then clip to `[CLIP_STD_MIN, CLIP_STD_MAX]`. The Bessel factor is part
/// of the pinned behavior (mutation that must turn the fixture tests red:
/// dropping the `n/(n−1)`).
fn clipped_std_along(x: &MlxArray, axis: i32, n: i32) -> UniquePtr<MlxArray> {
    let mean = ffi::mean_axis(x, axis, true);
    let sq_mean = ffi::mean_axis(&ffi::multiply(x, x), axis, true);
    let var = ffi::subtract(&sq_mean, &ffi::multiply(&mean, &mean));
    let bessel = n as f32 / (n - 1) as f32;
    let var = ffi::maximum(
        &crate::ops::multiply_scalar(&var, bessel),
        &ffi::full_like(&var, 0.0),
    );
    let std = ffi::sqrt(&var);
    ffi::clip(
        &std,
        &ffi::full_like(&std, CLIP_STD_MIN),
        &ffi::full_like(&std, CLIP_STD_MAX),
    )
}

/// Scalar imbalance metric of a `[N, R, C]` batch: `col_max/col_min +
/// row_max/row_min` over the GLOBAL batch (a perfectly balanced batch scores
/// 2.0).
///
/// Faithful-to-reference quirk, kept deliberately: the reference's batched
/// path annotates this `[N, 1, 1]` but computes `mx.max(...)` with no axis —
/// a GLOBAL scalar — so best-so-far selection is batch-global, not per-tile.
/// The pinned fixtures encode that behavior; changing it to per-tile would
/// be a (possibly better) deviation to take consciously, with regenerated
/// fixtures, not by accident.
fn imbalance(x: &MlxArray) -> UniquePtr<MlxArray> {
    let shape = ffi::array_shape(x);
    let (r, c) = (shape[shape.len() - 2], shape[shape.len() - 1]);
    let col_std = clipped_std_raw(x, -2, r);
    let row_std = clipped_std_raw(x, -1, c);
    let col_ratio = ffi::divide(
        &ffi::max_all(&col_std),
        &ffi::maximum(
            &ffi::min_all(&col_std),
            &ffi::full_f32(&[], 1e-8, dtype::FLOAT32),
        ),
    );
    let row_ratio = ffi::divide(
        &ffi::max_all(&row_std),
        &ffi::maximum(
            &ffi::min_all(&row_std),
            &ffi::full_f32(&[], 1e-8, dtype::FLOAT32),
        ),
    );
    ffi::add(&col_ratio, &row_ratio)
}

/// Std for the imbalance metric: Bessel-corrected but UNclipped (the
/// reference's `_imbalance` floors only the min at 1e-8, applied above).
fn clipped_std_raw(x: &MlxArray, axis: i32, n: i32) -> UniquePtr<MlxArray> {
    let mean = ffi::mean_axis(x, axis, true);
    let sq_mean = ffi::mean_axis(&ffi::multiply(x, x), axis, true);
    let var = ffi::subtract(&sq_mean, &ffi::multiply(&mean, &mean));
    let bessel = n as f32 / (n - 1) as f32;
    let var = ffi::maximum(
        &crate::ops::multiply_scalar(&var, bessel),
        &ffi::full_like(&var, 0.0),
    );
    ffi::sqrt(&var)
}

/// Log-domain Sinkhorn variance normalization over a `[N, R, C]` batch of
/// (already rotated) tiles.
///
/// Returns `(balanced, s_col, s_row)` with `balanced = tiles / s_col /
/// s_row`, `s_col: [N, 1, C]`, `s_row: [N, R, 1]` — the best-so-far scales
/// by the [`imbalance`] metric across `iterations` alternating column/row
/// passes. Faithful port of the reference `variance_normalize_batched`.
pub fn sinkhorn_normalize(
    tiles: &MlxArray,
    iterations: usize,
) -> (
    UniquePtr<MlxArray>,
    UniquePtr<MlxArray>,
    UniquePtr<MlxArray>,
) {
    let shape = ffi::array_shape(tiles);
    assert!(
        shape.len() == 3,
        "sinkhorn_normalize expects [N, R, C], got {shape:?}"
    );
    let (n, r, c) = (shape[0], shape[1], shape[2]);
    let tiles_f32 = ffi::astype(tiles, dtype::FLOAT32);

    let mut log_s_col = ffi::zeros(&[n, 1, c], dtype::FLOAT32);
    let mut log_s_row = ffi::zeros(&[n, r, 1], dtype::FLOAT32);

    let mut sc_best = ffi::exp(&log_s_col);
    let mut sr_best = ffi::exp(&log_s_row);
    let mut imb_best = imbalance(&tiles_f32);

    let clip_log = |v: &MlxArray| -> UniquePtr<MlxArray> {
        ffi::clip(
            v,
            &ffi::full_like(v, LOG_S_MIN),
            &ffi::full_like(v, LOG_S_MAX),
        )
    };

    let mut cur = ffi::astype(&tiles_f32, dtype::FLOAT32);
    for _ in 0..iterations {
        // Column pass.
        let col_std = clipped_std_along(&cur, -2, r);
        log_s_col = clip_log(&ffi::add(&log_s_col, &ffi::log(&col_std)));
        let s_col_lin = ffi::exp(&log_s_col);
        let s_row_lin = ffi::exp(&log_s_row);
        cur = ffi::divide(&ffi::divide(&tiles_f32, &s_col_lin), &s_row_lin);

        // Row pass.
        let row_std = clipped_std_along(&cur, -1, c);
        log_s_row = clip_log(&ffi::add(&log_s_row, &ffi::log(&row_std)));
        let s_col_lin = ffi::exp(&log_s_col);
        let s_row_lin = ffi::exp(&log_s_row);
        cur = ffi::divide(&ffi::divide(&tiles_f32, &s_col_lin), &s_row_lin);

        // Best-so-far (batch-global — see `imbalance` docs).
        let imb = imbalance(&cur);
        let better = ffi::less_equal(&imb, &imb_best);
        sc_best = ffi::where_cond(&better, &s_col_lin, &sc_best);
        sr_best = ffi::where_cond(&better, &s_row_lin, &sr_best);
        imb_best = ffi::minimum(&imb, &imb_best);
    }

    let balanced = ffi::divide(&ffi::divide(&tiles_f32, &sc_best), &sr_best);
    (balanced, sc_best, sr_best)
}

/// Per-row asymmetric round-to-nearest quantization of `[N, R, C]` balanced
/// tiles to `bits` (8 or 4). Returns `(q_u8, scale, zp)` with the exact
/// reference semantics: `scale = max((hi − lo)/qmax, 1e-10)`, `zp = lo`,
/// `q = clip(round((x − zp)/scale), 0, qmax)`.
pub fn rtn_quantize_per_row(
    tiles: &MlxArray,
    bits: u8,
) -> (
    UniquePtr<MlxArray>,
    UniquePtr<MlxArray>,
    UniquePtr<MlxArray>,
) {
    assert!(
        bits == 8 || bits == 4,
        "KVarN RTN supports bits 8 or 4, got {bits}"
    );
    let qmax = ((1u32 << bits) - 1) as f32;
    let lo = ffi::min_axis(tiles, -1, true);
    let hi = ffi::max_axis(tiles, -1, true);
    let range = ffi::subtract(&hi, &lo);
    let scale = ffi::maximum(
        &crate::ops::divide_scalar(&range, qmax),
        &ffi::full_like(&range, 1e-10),
    );
    let centered = ffi::divide(&ffi::subtract(tiles, &lo), &scale);
    let q = ffi::clip(
        &ffi::round(&centered),
        &ffi::full_like(&centered, 0.0),
        &ffi::full_like(&centered, qmax),
    );
    (ffi::astype(&q, dtype::UINT8), scale, lo)
}

/// Full write-side pipeline on ROTATED tiles: Sinkhorn → RTN.
///
/// Callers rotate first ([`kvarn_rotate`]) — rotation is per-token and can
/// happen on arrival, while Sinkhorn+RTN happen per full tile.
pub fn kvarn_quantize(tiles_rotated: &MlxArray, bits: u8) -> KvarnQuantizedTiles {
    let (balanced, s_col, s_row) = sinkhorn_normalize(tiles_rotated, KVARN_SINKHORN_ITERS);
    let (q, scale, zp) = rtn_quantize_per_row(&balanced, bits);
    KvarnQuantizedTiles {
        q,
        scale,
        zp,
        s_col,
        s_row,
        bits,
    }
}

/// Read-side dequantization back to the ROTATED frame:
/// `(q · scale + zp) · s_col · s_row`. One more [`kvarn_rotate`] (self-
/// inverse) yields standard-frame tensors.
pub fn kvarn_dequantize_rotated(t: &KvarnQuantizedTiles) -> UniquePtr<MlxArray> {
    let qf = ffi::astype(&t.q, dtype::FLOAT32);
    let de = ffi::add(&ffi::multiply(&qf, &t.scale), &t.zp);
    ffi::multiply(&ffi::multiply(&de, &t.s_col), &t.s_row)
}

#[cfg(test)]
mod tests {
    use super::*;

    // Fixtures generated by scripts/export_kvarn_fixtures.py from the
    // mlx-kvarn REFERENCE implementation (2 tiles, [2,128,128], f32 LE,
    // sinkhorn_iters=4, seed 42, ×40 outlier channels). Shapes per
    // kvarn_fixtures/manifest.json.
    const N: i32 = 2;
    const R: i32 = 128;
    const C: i32 = 128;

    fn fixture_f32(bytes: &'static [u8], shape: &[i32]) -> cxx::UniquePtr<MlxArray> {
        let n_expected: usize = shape.iter().product::<i32>() as usize;
        assert_eq!(bytes.len(), n_expected * 4, "fixture size mismatch");
        let vals: Vec<f32> = bytes
            .chunks_exact(4)
            .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
            .collect();
        ffi::from_slice_f32(&vals, shape)
    }

    fn fixture_u8_as_f32_array(bytes: &'static [u8], shape: &[i32]) -> cxx::UniquePtr<MlxArray> {
        let n_expected: usize = shape.iter().product::<i32>() as usize;
        assert_eq!(bytes.len(), n_expected, "fixture size mismatch");
        let vals: Vec<f32> = bytes.iter().map(|&b| b as f32).collect();
        ffi::from_slice_f32(&vals, shape)
    }

    /// Count of elements where |a − b| > 0.5 (i.e. integer codes differing).
    fn code_mismatch_count(a: &MlxArray, b: &MlxArray) -> f32 {
        let diff = ffi::abs(&ffi::subtract(a, b));
        let hits = ffi::greater(&diff, &ffi::full_like(&diff, 0.5));
        let count = ffi::sum_all(&ffi::astype(&hits, dtype::FLOAT32));
        ffi::eval(&count);
        ffi::item_f32(&count)
    }

    fn max_abs_rel_diff(a: &MlxArray, b: &MlxArray) -> (f32, f32) {
        let diff = ffi::abs(&ffi::subtract(a, b));
        let max_abs = ffi::max_all(&diff);
        let denom = ffi::maximum(&ffi::abs(b), &ffi::full_like(b, 1e-6));
        let max_rel = ffi::max_all(&ffi::divide(&diff, &denom));
        ffi::eval(&max_abs);
        ffi::eval(&max_rel);
        (ffi::item_f32(&max_abs), ffi::item_f32(&max_rel))
    }

    const INPUT: &[u8] = include_bytes!("kvarn_fixtures/input_tiles_f32.bin");
    const ROTATED: &[u8] = include_bytes!("kvarn_fixtures/rotated_f32.bin");
    const BALANCED: &[u8] = include_bytes!("kvarn_fixtures/balanced_f32.bin");
    const S_COL: &[u8] = include_bytes!("kvarn_fixtures/s_col_f32.bin");
    const S_ROW: &[u8] = include_bytes!("kvarn_fixtures/s_row_f32.bin");
    const Q8: &[u8] = include_bytes!("kvarn_fixtures/q8_u8.bin");
    const SCALE8: &[u8] = include_bytes!("kvarn_fixtures/scale8_f32.bin");
    const ZP8: &[u8] = include_bytes!("kvarn_fixtures/zp8_f32.bin");
    const DEQ_ROT8: &[u8] = include_bytes!("kvarn_fixtures/dequant_rot8_f32.bin");
    const Q4: &[u8] = include_bytes!("kvarn_fixtures/q4_u8.bin");

    /// Stage 1: our rotation reproduces the reference's rotated tiles.
    /// Mutation that must turn this red: any scale change on `wht` (the
    /// orthonormal 1/√N convention is load-bearing for round-trip).
    #[test]
    fn kvarn_rotate_matches_reference() {
        let x = fixture_f32(INPUT, &[N, R, C]);
        let rot = kvarn_rotate(&x);
        let expected = fixture_f32(ROTATED, &[N, R, C]);
        let (max_abs, _) = max_abs_rel_diff(&rot, &expected);
        assert!(
            max_abs < 1e-3,
            "rotation diverges from reference: {max_abs}"
        );
    }

    /// Stage 2: Sinkhorn balanced tiles + both scale vectors match the
    /// reference at 4 iterations. Mutations that must turn this red:
    /// dropping the Bessel n/(n−1); swapping the clip bounds; skipping the
    /// second (row) pass; best-so-far tracking removed.
    #[test]
    fn kvarn_sinkhorn_matches_reference() {
        let rot = fixture_f32(ROTATED, &[N, R, C]);
        let (balanced, s_col, s_row) = sinkhorn_normalize(&rot, 4);
        let exp_bal = fixture_f32(BALANCED, &[N, R, C]);
        let exp_sc = fixture_f32(S_COL, &[N, 1, C]);
        let exp_sr = fixture_f32(S_ROW, &[N, R, 1]);
        let (abs_b, _) = max_abs_rel_diff(&balanced, &exp_bal);
        let (_, rel_c) = max_abs_rel_diff(&s_col, &exp_sc);
        let (_, rel_r) = max_abs_rel_diff(&s_row, &exp_sr);
        assert!(abs_b < 1e-2, "balanced tiles diverge: max_abs={abs_b}");
        assert!(rel_c < 1e-3, "s_col diverges: max_rel={rel_c}");
        assert!(rel_r < 1e-3, "s_row diverges: max_rel={rel_r}");
    }

    /// Stage 3 (k8): RTN codes match the reference EXACTLY (integers), and
    /// scale/zp match tightly. Mutation that must turn this red: symmetric
    /// instead of asymmetric quantization (zp = 0), or qmax 256 vs 255.
    #[test]
    fn kvarn_rtn8_matches_reference_exactly() {
        let balanced = fixture_f32(BALANCED, &[N, R, C]);
        let (q, scale, zp) = rtn_quantize_per_row(&balanced, 8);
        let qf = ffi::astype(&q, dtype::FLOAT32);
        let expected = fixture_u8_as_f32_array(Q8, &[N, R, C]);
        // ±1 code tolerance on exact rounding boundaries would be defensible
        // across MLX versions; with the SAME MLX on both sides we hold exact.
        let mismatches = code_mismatch_count(&qf, &expected);
        assert_eq!(
            mismatches, 0.0,
            "{mismatches} q8 codes differ from reference"
        );

        let exp_scale = fixture_f32(SCALE8, &[N, R, 1]);
        let exp_zp = fixture_f32(ZP8, &[N, R, 1]);
        let (_, rel_s) = max_abs_rel_diff(&scale, &exp_scale);
        let (abs_z, _) = max_abs_rel_diff(&zp, &exp_zp);
        assert!(rel_s < 1e-4, "scale8 diverges: {rel_s}");
        assert!(abs_z < 1e-3, "zp8 diverges: {abs_z}");
    }

    /// Stage 3 (k4): same pinning at 4 bits.
    #[test]
    fn kvarn_rtn4_matches_reference_exactly() {
        let balanced = fixture_f32(BALANCED, &[N, R, C]);
        let (q, _, _) = rtn_quantize_per_row(&balanced, 4);
        let qf = ffi::astype(&q, dtype::FLOAT32);
        let expected = fixture_u8_as_f32_array(Q4, &[N, R, C]);
        let mismatches = code_mismatch_count(&qf, &expected);
        assert_eq!(
            mismatches, 0.0,
            "{mismatches} q4 codes differ from reference"
        );
    }

    /// Stage 4: rotated-frame dequantization matches the reference's
    /// dequant, i.e. the full read path reproduces what the write path
    /// stored, per the reference math.
    #[test]
    fn kvarn_dequant_rotated_matches_reference() {
        let rot = fixture_f32(ROTATED, &[N, R, C]);
        let tiles = kvarn_quantize(&rot, 8);
        let deq = kvarn_dequantize_rotated(&tiles);
        let expected = fixture_f32(DEQ_ROT8, &[N, R, C]);
        let (max_abs, _) = max_abs_rel_diff(&deq, &expected);
        assert!(
            max_abs < 5e-2,
            "rotated dequant diverges: max_abs={max_abs}"
        );
    }

    /// End-to-end roundtrip on the ORIGINAL tiles: rotate → quantize →
    /// dequantize → unrotate ≈ input, with the k8 error band from the
    /// decomposition experiment (rel_err ≈ 0.004; assert an order of
    /// margin). Also asserts the band is TIGHT: a fake pipeline that
    /// skipped Sinkhorn entirely would land near absmax-int8's error and
    /// fail the upper bound... while a broken one fails the lower bound of
    /// simply being finite and nonzero.
    #[test]
    fn kvarn_k8_end_to_end_roundtrip_error_band() {
        let x = fixture_f32(INPUT, &[N, R, C]);
        let rot = kvarn_rotate(&x);
        let tiles = kvarn_quantize(&rot, 8);
        let deq_rot = kvarn_dequantize_rotated(&tiles);
        let back = kvarn_rotate(&deq_rot); // self-inverse
        let diff = ffi::subtract(&back, &x);
        let num = ffi::sqrt(&ffi::sum_all(&ffi::multiply(&diff, &diff)));
        let den = ffi::sqrt(&ffi::sum_all(&ffi::multiply(&x, &x)));
        let rel = ffi::divide(&num, &den);
        ffi::eval(&rel);
        let rel = ffi::item_f32(&rel);
        assert!(rel < 0.02, "k8 roundtrip rel_err {rel} above expected band");
        assert!(
            rel > 1e-5,
            "k8 roundtrip rel_err {rel} suspiciously exact — \
                 is quantization actually happening?"
        );
    }
}

#[cfg(test)]
mod cache_integration_tests {
    use super::*;
    use crate::cache::{KVCache, KVCacheMode};

    /// Deterministic pseudo-random f32 in [-1, 1) — no MLX RNG plumbing
    /// needed, and fully reproducible across runs/platforms.
    fn lcg_data(n: usize, seed: u64) -> Vec<f32> {
        let mut state = seed;
        (0..n)
            .map(|_| {
                state = state
                    .wrapping_mul(6364136223846793005)
                    .wrapping_add(1442695040888963407);
                ((state >> 33) as f32 / (1u64 << 31) as f32) - 1.0
            })
            .collect()
    }

    /// End-to-end: a KVarN8 KVCache and an Fp16 KVCache fed IDENTICAL data
    /// through the real update_and_fetch, compared after every chunk.
    ///
    /// Chunk sizes exercise every split path in update_kvarn8:
    ///   200 → sink fills (128) + tail 72
    ///   100 → tail 172 → one tile quantized (128) + tail 44
    ///   1   → decode-shaped single, tail 45
    ///   83  → tail 128 → EXACT tile boundary (tile quantized, tail empty)
    ///   1   → first token into a fresh tail
    ///
    /// The k8 band from the decomposition experiment is rel_err ≈ 0.004 on
    /// f32 tiles; fp16 in/out adds ~1e-3. Assert mean-square relative error
    /// < 0.02 AND > 1e-6 (a bit-exact match would mean quantization never
    /// ran — the sink-only prefix IS expected to be near-exact, so the
    /// lower bound is asserted only once history tiles exist).
    #[test]
    fn kvarn8_cache_roundtrip_tracks_fp16_within_band() {
        let (b, h, d) = (1i32, 2i32, 64i32);
        let mut kvarn = KVCache::new_with_mode(KVCacheMode::KVarN8);
        let mut fp16 = KVCache::new_with_mode(KVCacheMode::Fp16);

        let mut total = 0i32;
        for (i, &chunk) in [200i32, 100, 1, 83, 1].iter().enumerate() {
            let n = (b * h * chunk * d) as usize;
            let k_data = lcg_data(n, 0xC1E_A0 + i as u64);
            let v_data = lcg_data(n, 0xB0_B0 + i as u64);
            let shape = [b, h, chunk, d];
            let mk = || {
                (
                    ffi::astype(&ffi::from_slice_f32(&k_data, &shape), dtype::FLOAT16),
                    ffi::astype(&ffi::from_slice_f32(&v_data, &shape), dtype::FLOAT16),
                )
            };
            let (k1, v1) = mk();
            let (k2, v2) = mk();
            let (qk, qv) = kvarn.update_and_fetch(k1, v1);
            let (rk, rv) = fp16.update_and_fetch(k2, v2);
            total += chunk;

            for (q, r, name) in [(&qk, &rk, "K"), (&qv, &rv, "V")] {
                assert_eq!(
                    ffi::array_shape(q),
                    ffi::array_shape(r),
                    "{name} shape mismatch after chunk {i}"
                );
                assert_eq!(ffi::array_shape(q)[2], total, "{name} window length");
                let qf = ffi::astype(q, dtype::FLOAT32);
                let rf = ffi::astype(r, dtype::FLOAT32);
                let diff = ffi::subtract(&qf, &rf);
                let num = ffi::sum_all(&ffi::multiply(&diff, &diff));
                let den = ffi::sum_all(&ffi::multiply(&rf, &rf));
                let rel = ffi::divide(&ffi::sqrt(&num), &ffi::sqrt(&den));
                ffi::eval(&rel);
                let rel = ffi::item_f32(&rel);
                assert!(
                    rel < 0.02,
                    "{name} rel_err {rel} above k8 band after chunk {i} (total={total})"
                );
                if total > 2 * KVARN_TILE_TOKENS {
                    // History tiles exist — quantization must be visible.
                    assert!(
                        rel > 1e-6,
                        "{name} suspiciously exact after chunk {i} — is \
                         quantization actually running?"
                    );
                }
            }
        }
    }

    /// The trim_front guard must keep refusing KVarN8 (tile state cannot be
    /// head-trimmed) — pin the guard's current behavior so a future edit
    /// widening the matches! turns this red instead of corrupting silently.
    #[test]
    fn kvarn8_trim_front_refuses() {
        let mut cache = KVCache::new_with_mode(KVCacheMode::KVarN8);
        let (b, h, d) = (1i32, 1i32, 64i32);
        let n = (b * h * 200 * d) as usize;
        let k = ffi::astype(
            &ffi::from_slice_f32(&lcg_data(n, 7), &[b, h, 200, d]),
            dtype::FLOAT16,
        );
        let v = ffi::astype(
            &ffi::from_slice_f32(&lcg_data(n, 8), &[b, h, 200, d]),
            dtype::FLOAT16,
        );
        let _ = cache.update_and_fetch(k, v);
        let trimmed = cache.trim_front(64);
        assert_eq!(
            trimmed, 0,
            "KVarN8 must refuse head-trimming (returned {trimmed})"
        );
    }
}

#[cfg(test)]
mod detach_roundtrip_tests {
    use super::*;
    use crate::cache::{KVCache, KVCacheMode};

    fn lcg_data(n: usize, seed: u64) -> Vec<f32> {
        let mut state = seed;
        (0..n)
            .map(|_| {
                state = state
                    .wrapping_mul(6364136223846793005)
                    .wrapping_add(1442695040888963407);
                ((state >> 33) as f32 / (1u64 << 31) as f32) - 1.0
            })
            .collect()
    }

    fn feed(cache: &mut KVCache, data_k: &[f32], data_v: &[f32], b: i32, h: i32, len: i32, d: i32) {
        let k = ffi::astype(
            &ffi::from_slice_f32(data_k, &[b, h, len, d]),
            dtype::FLOAT16,
        );
        let v = ffi::astype(
            &ffi::from_slice_f32(data_v, &[b, h, len, d]),
            dtype::FLOAT16,
        );
        let _ = cache.update_and_fetch(k, v);
    }

    /// PR-3 proof: detach → tile-aligned trim → adopt into a fresh cache
    /// must be BIT-IDENTICAL to a cache that simply never saw the trimmed
    /// suffix — the surviving quantized tiles are the same bytes, the
    /// pipeline is deterministic, so any divergence is a slicing bug.
    ///
    /// 320 tokens = sink 128 + one 128-token tile + tail 64.
    /// trim_to(256) keeps sink + tile exactly (the aligned boundary).
    /// Both caches then receive the same next token; the fetched windows
    /// must match exactly (atol 0 via allclose with tight tolerances).
    #[test]
    fn kvarn8_detach_trim_adopt_is_bit_identical_to_direct_prefix() {
        let (b, h, d) = (1i32, 2i32, 64i32);
        let n_all = (b * h * 320 * d) as usize;
        let k_all = lcg_data(n_all, 0xDE7AC0);
        let v_all = lcg_data(n_all, 0xAD0B7);

        // Cache A: all 320 tokens, then detach + trim to 256 + adopt.
        let mut a = KVCache::new_with_mode(KVCacheMode::KVarN8);
        feed(&mut a, &k_all, &v_all, b, h, 320, d);
        let mut detached = a.clone_handle();
        detached
            .trim_to(256)
            .expect("tile-aligned trim must succeed");
        let mut adopted = KVCache::new_with_mode(KVCacheMode::KVarN8);
        adopted
            .install_detached(detached)
            .expect("install into fresh cache");
        assert_eq!(adopted.offset, 256, "adopted offset");

        // Cache B: fed ONLY the first 256 tokens of the identical stream.
        // Per-(head,token) layout means the first 256 tokens of each head
        // are interleaved in the flat buffer — slice via MLX, not the Vec.
        let mut direct = KVCache::new_with_mode(KVCacheMode::KVarN8);
        let k_full = ffi::from_slice_f32(&k_all, &[b, h, 320, d]);
        let v_full = ffi::from_slice_f32(&v_all, &[b, h, 320, d]);
        let k_256 = ffi::slice(&k_full, &[0, 0, 0, 0], &[b, h, 256, d]);
        let v_256 = ffi::slice(&v_full, &[0, 0, 0, 0], &[b, h, 256, d]);
        let _ = direct.update_and_fetch(
            ffi::astype(&k_256, dtype::FLOAT16),
            ffi::astype(&v_256, dtype::FLOAT16),
        );

        // Same next token to both; windows must match bit-for-bit.
        let n1 = (b * h * d) as usize;
        let k_next = lcg_data(n1, 999);
        let v_next = lcg_data(n1, 998);
        let mk =
            |data: &[f32]| ffi::astype(&ffi::from_slice_f32(data, &[b, h, 1, d]), dtype::FLOAT16);
        let (qa_k, qa_v) = adopted.update_and_fetch(mk(&k_next), mk(&v_next));
        let (qb_k, qb_v) = direct.update_and_fetch(mk(&k_next), mk(&v_next));

        for (x, y, name) in [(&qa_k, &qb_k, "K"), (&qa_v, &qb_v, "V")] {
            assert_eq!(ffi::array_shape(x), ffi::array_shape(y), "{name} shape");
            assert_eq!(ffi::array_shape(x)[2], 257, "{name} window len");
            let close = ffi::allclose(x, y, 0.0, 1e-6);
            ffi::eval(&close);
            assert!(
                ffi::item_bool(&close),
                "{name}: adopted-after-trim diverges from direct prefix — \
                 detach/trim/install corrupted tile state"
            );
        }
    }

    /// Misaligned history truncation must refuse loudly, not approximate.
    #[test]
    fn kvarn8_trim_to_refuses_misaligned_history() {
        let (b, h, d) = (1i32, 1i32, 64i32);
        let n = (b * h * 320 * d) as usize;
        let mut cache = KVCache::new_with_mode(KVCacheMode::KVarN8);
        feed(&mut cache, &lcg_data(n, 41), &lcg_data(n, 42), b, h, 320, d);
        let mut detached = cache.clone_handle();
        // 200 = sink 128 + 72 tokens INTO the tile — not tile-aligned.
        let err = detached.trim_to(200);
        assert!(
            err.is_err(),
            "misaligned KVarN8 trim must fail loudly, got Ok"
        );
        let msg = err.unwrap_err();
        assert!(
            msg.contains("tile-aligned"),
            "error must name the alignment violation: {msg}"
        );
    }

    /// Trim INTO the sink region (below one tile) keeps a pure-FP16 prefix.
    #[test]
    fn kvarn8_trim_to_within_sink() {
        let (b, h, d) = (1i32, 1i32, 64i32);
        let n = (b * h * 320 * d) as usize;
        let mut cache = KVCache::new_with_mode(KVCacheMode::KVarN8);
        feed(&mut cache, &lcg_data(n, 51), &lcg_data(n, 52), b, h, 320, d);
        let mut detached = cache.clone_handle();
        detached.trim_to(64).expect("sink-region trim");
        let mut adopted = KVCache::new_with_mode(KVCacheMode::KVarN8);
        adopted.install_detached(detached).expect("install");
        assert_eq!(adopted.offset, 64);
        // Continue generating from it — window must be 65 after one token.
        let n1 = (b * h * d) as usize;
        let k = ffi::astype(
            &ffi::from_slice_f32(&lcg_data(n1, 61), &[b, h, 1, d]),
            dtype::FLOAT16,
        );
        let v = ffi::astype(
            &ffi::from_slice_f32(&lcg_data(n1, 62), &[b, h, 1, d]),
            dtype::FLOAT16,
        );
        let (kk, _) = adopted.update_and_fetch(k, v);
        assert_eq!(ffi::array_shape(&kk)[2], 65, "window after sink-trim + 1");
    }
}

/// K1 gate (DESIGN_fused_msa_kvarn_decode_plan §K1): block-fetch must be
/// BITWISE identical to the corresponding slices of the full window —
/// the in-engine pin of the K0 reference result (Q1: per-tile dequant is
/// independent; Q3: the inverse WHT is per-token, so it commutes with
/// block selection).
#[cfg(test)]
mod block_fetch_tests {
    use super::*;
    use crate::cache::{KVCache, KVCacheMode};

    fn lcg_data(n: usize, seed: u64) -> Vec<f32> {
        let mut state = seed;
        (0..n)
            .map(|_| {
                state = state
                    .wrapping_mul(6364136223846793005)
                    .wrapping_add(1442695040888963407);
                ((state >> 33) as f32 / (1u64 << 31) as f32) - 1.0
            })
            .collect()
    }

    /// sink 128 + 3 tiles + tail 45 = 557 tokens; request a mixed-format
    /// block list (sink, interior tiles, the padded tail block) and pin
    /// every block against the full window, bit-for-bit (atol 0).
    #[test]
    fn kvarn_block_fetch_matches_full_window() {
        let (b, h, d) = (1i32, 2i32, 64i32);
        let total = 557i32; // 128 + 3*128 + 45
        let tail_len = 45i32;
        let n = (b * h * total * d) as usize;
        let k_data = lcg_data(n, 0xB10C5);
        let v_data = lcg_data(n, 0xB10C6);

        let mut cache = KVCache::new_with_mode(KVCacheMode::KVarN8);
        assert!(
            cache.supports_block_fetch(),
            "kvarn8 must support block fetch"
        );
        let mk = |data: &[f32]| {
            ffi::astype(
                &ffi::from_slice_f32(data, &[b, h, total, d]),
                dtype::FLOAT16,
            )
        };
        let (k_full, v_full) = cache.update_and_fetch(mk(&k_data), mk(&v_data));
        assert_eq!(ffi::array_shape(&k_full)[2], total, "full window len");

        // Mixed list: sink (0), tiles (1,3), tail block (4).
        let blocks = [0i32, 1, 3, 4];
        let (k_blk, v_blk) = cache.fetch_kvarn8_blocks(&blocks);
        assert_eq!(
            ffi::array_shape(&k_blk),
            vec![b, h, blocks.len() as i32 * KVARN_TILE_TOKENS, d],
            "compact shape"
        );

        for (full, compact, name) in [(&k_full, &k_blk, "K"), (&v_full, &v_blk, "V")] {
            for (i, &blk) in blocks.iter().enumerate() {
                let src0 = blk * KVARN_TILE_TOKENS;
                let src1 = (src0 + KVARN_TILE_TOKENS).min(total);
                let blk_len = src1 - src0; // 128 except the tail block (45)
                let dst0 = i as i32 * KVARN_TILE_TOKENS;
                let want = ffi::slice(full, &[0, 0, src0, 0], &[b, h, src1, d]);
                let got = ffi::slice(compact, &[0, 0, dst0, 0], &[b, h, dst0 + blk_len, d]);
                let close = ffi::allclose(&got, &want, 0.0, 0.0);
                ffi::eval(&close);
                assert!(
                    ffi::item_bool(&close),
                    "{name} block {blk}: compact fetch diverges from full window"
                );
                // Tail block: the padded region must be EXACTLY zero, so
                // the caller's position mask is the only thing standing
                // between padding and attention — same contract as the v1
                // path's fp16 zero-padding in sparse_decode_attention.
                if blk_len < KVARN_TILE_TOKENS {
                    let pad = ffi::slice(
                        compact,
                        &[0, 0, dst0 + blk_len, 0],
                        &[b, h, dst0 + KVARN_TILE_TOKENS, d],
                    );
                    let zeros =
                        ffi::full_f32(&[b, h, KVARN_TILE_TOKENS - blk_len, d], 0.0, dtype::FLOAT16);
                    let pz = ffi::allclose(&pad, &zeros, 0.0, 0.0);
                    ffi::eval(&pz);
                    assert!(ffi::item_bool(&pz), "{name} tail padding must be zero");
                }
            }
        }
        let _ = tail_len; // geometry documented above
    }

    /// A tail-less window (total = sink + exact tiles): last_block is the
    /// final TILE, and requesting one block only must work (top_k=1 shape).
    #[test]
    fn kvarn_block_fetch_tailless_and_single() {
        let (b, h, d) = (1i32, 1i32, 64i32);
        let total = 384i32; // 128 sink + 2 tiles, no tail
        let n = (b * h * total * d) as usize;
        let mut cache = KVCache::new_with_mode(KVCacheMode::KVarN8);
        let mk = |data: &[f32]| {
            ffi::astype(
                &ffi::from_slice_f32(data, &[b, h, total, d]),
                dtype::FLOAT16,
            )
        };
        let (k_full, _) = cache.update_and_fetch(mk(&lcg_data(n, 7)), mk(&lcg_data(n, 8)));

        let (k_blk, _) = cache.fetch_kvarn8_blocks(&[2]);
        let want = ffi::slice(&k_full, &[0, 0, 256, 0], &[b, h, 384, d]);
        let close = ffi::allclose(&k_blk, &want, 0.0, 0.0);
        ffi::eval(&close);
        assert!(ffi::item_bool(&close), "single interior tile fetch");
    }

    #[test]
    #[should_panic(expected = "strictly increasing")]
    fn kvarn_block_fetch_refuses_unsorted() {
        let (b, h, d) = (1i32, 1i32, 64i32);
        let total = 384i32;
        let n = (b * h * total * d) as usize;
        let mut cache = KVCache::new_with_mode(KVCacheMode::KVarN8);
        let mk = |data: &[f32]| {
            ffi::astype(
                &ffi::from_slice_f32(data, &[b, h, total, d]),
                dtype::FLOAT16,
            )
        };
        let _ = cache.update_and_fetch(mk(&lcg_data(n, 9)), mk(&lcg_data(n, 10)));
        let _ = cache.fetch_kvarn8_blocks(&[2, 1]);
    }

    #[test]
    #[should_panic(expected = "in-range")]
    fn kvarn_block_fetch_refuses_out_of_range() {
        let (b, h, d) = (1i32, 1i32, 64i32);
        let total = 384i32; // last_block = 2 (no tail)
        let n = (b * h * total * d) as usize;
        let mut cache = KVCache::new_with_mode(KVCacheMode::KVarN8);
        let mk = |data: &[f32]| {
            ffi::astype(
                &ffi::from_slice_f32(data, &[b, h, total, d]),
                dtype::FLOAT16,
            )
        };
        let _ = cache.update_and_fetch(mk(&lcg_data(n, 11)), mk(&lcg_data(n, 12)));
        let _ = cache.fetch_kvarn8_blocks(&[0, 3]);
    }

    /// fp16 caches must report no block-fetch support (the model-side
    /// dispatch keys on this — a wrong `true` would route fp16 decode into
    /// a method that panics on missing kvarn state).
    #[test]
    fn fp16_cache_does_not_support_block_fetch() {
        let cache = KVCache::new_with_mode(KVCacheMode::Fp16);
        assert!(!cache.supports_block_fetch());
    }
}

/// The indexer-cache capacity buffer (m3_idx_k_update_and_fetch) must be
/// invisible to readers: exact-length windows with exactly the appended
/// values, across the 4096-token growth boundary, and slice-to-fill on
/// detach. This is the contract the concat-based implementation met by
/// construction; the capacity-buffer rewrite must meet it byte-for-byte.
#[cfg(test)]
mod m3_idx_capacity_tests {
    use super::*;
    use crate::cache::KVCache;

    fn chunk(vals_base: f32, len: i32, dim: i32) -> UniquePtr<MlxArray> {
        let data: Vec<f32> = (0..len * dim).map(|i| vals_base + i as f32).collect();
        ffi::from_slice_f32(&data, &[1, 1, len, dim])
    }

    fn window_as_vec(w: &MlxArray) -> Vec<f32> {
        ffi::eval(w);
        ffi::array_to_raw_bytes(w)
            .chunks_exact(4)
            .map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]]))
            .collect()
    }

    #[test]
    fn m3_idx_capacity_growth_preserves_window() {
        let dim = 4i32;
        let mut cache = KVCache::new();
        let mut expected: Vec<f32> = Vec::new();
        let mut total = 0i32;

        // Chunks sized to cross 4096 twice-over: 40 x 130 = 5200 tokens.
        for i in 0..40 {
            let len = 130i32;
            let c = chunk((i * 100_000) as f32, len, dim);
            expected.extend((0..len * dim).map(|j| (i * 100_000) as f32 + j as f32));
            total += len;
            let win = cache.m3_idx_k_update_and_fetch(&c);
            assert_eq!(
                ffi::array_shape(&win),
                vec![1, 1, total, dim],
                "window shape after chunk {i} (fill {total})"
            );
            // Spot-check the FULL window contents at the boundaries where
            // the growth copy happens (before/at/after 4096) and the ends.
            if [0, 30, 31, 32, 39].contains(&i) {
                assert_eq!(
                    window_as_vec(&win),
                    expected,
                    "window contents diverged after chunk {i} — capacity \
                     growth copy or slice_update wrote the wrong region"
                );
            }
        }
        assert_eq!(cache.m3_idx_offset(), 5200);

        // Detach must carry the EXACT-length window (documented contract),
        // not the capacity buffer.
        let detached = cache.clone_handle();
        let idx = detached_m3_idx(&detached);
        assert_eq!(
            ffi::array_shape(idx),
            vec![1, 1, 5200, dim],
            "detached m3_idx_k must be sliced to fill, not capacity"
        );
        assert_eq!(window_as_vec(idx), expected, "detached contents");
    }

    fn detached_m3_idx(d: &crate::cache::DetachedKVCache) -> &MlxArray {
        d.m3_idx_k_for_tests()
            .expect("detached handle must carry m3_idx_k")
    }
}
